### ISSUE TITLE
客户端和服务端已经联通了，但是通过服务端无法访问内网站点，如下图

### ISSUE THREAD

**Issue by xier2012** [xljiulang/HttpMouse#2]
![image](https://user-images.githubusercontent.com/8035223/129534572-f70de10d-f982-4647-8ff5-a33d7d129cd5.png)
![image](https://user-images.githubusercontent.com/8035223/129534615-45f710ab-c42c-4203-b652-1805194d2815.png)
![image](https://user-images.githubusercontent.com/8035223/129534631-3f9ca0c9-2c77-4cbe-bced-8f8963f2925f.png)

**Comment by xljiulang** [comment]
clientDomain理解错误了，要配置为服务器某个域名，这里可以直接使用服务ip，也就是123.x.x.x

**Comment by xier2012** [comment]
![D7OFY$~))G ZMF9%4ZGITBS](https://user-images.githubusercontent.com/8035223/129647144-6560b43c-ce1c-4029-aae7-fb45f8309529.png)
clientDomain 设置为服务器IP后，服务端日志输出 创建反向连接超时

**Comment by xljiulang** [comment]
你直接集成代码还是?感觉你的配置和现有代码不匹配

**Comment by xljiulang** [comment]
你试试服务器与客户端在先在本机调通，再转到公网部署

**Comment by xier2012** [comment]
使用的是samples 里面的客户端和服务端程序；服务端和客户端都在本机测试是可以调通的；把服务端放到公网后，就不行了

**Comment by xljiulang** [comment]
客户端有什么日志吗

**Comment by xier2012** [comment]
客户端没有日志

**Comment by xljiulang** [comment]
服务器前面有反向代理软件吗，比如iis或niginx

**Comment by xier2012** [comment]
有IIS

**Comment by xljiulang** [comment]
去掉iis，因为使用了websocket
